### PR TITLE
Pull request for cloaked's hw2/hw1 changes + other stuff into Bleeding-Edge

### PR DESCRIPTION
**Pull request by cloaked2222**
Summary of changes (for build 8):
- Kus/Tai Tweaks for Fear's May/June changes
- Hiig/Vay Tweaks for Fear's May/June changes
- Observer Tweaks
- SP missing files (Not sure how these got missed, they are needed for the 2.3 campaign)
- SP bug fixes
- 2.205 campaign zips
- HW1 Design Spreadsheet

### CODE REVIEW

**Comment by Novaras** [comment]
We need to discuss what your idea is for these large scale changes. I have no desire to implement any of it into v8 which is already shipping with a huge changelog itself.

From my understanding all of this is targeted at v9, so there's no reason for it to be pulled into bleeding edge... which is our v8 branch?

**Comment by cloaked2222** [comment]
These are all b8 changes, nothing from b9.

See here for more info:
https://github.com/HW-PlayersPatch/2.3/issues/60#issuecomment-401457025

**Comment by Novaras** [comment]
This is a monumental overwrite of 99 files... well over 60 of which are MP; hs plat regen is gone for example, none of the props are updated, scouts lost an additional 30 visual range... these are just surface level scans as im scrolling down, where are these changes in the issues? Did I miss some stuff?

Stuff we have since discussed in issues such as light vette speed is still aligned with 'old' values. I must be being really stupid today, maybe because I've not been following this project closely the past fortnight. As I understand the content of this branch right now, why on earth would we want to merge this into bleeding edge? We would *lose* a ton of progress?

**Comment by cloaked2222** [comment]
Updated some things per discussions. Been 3 weeks now so merging this in.

**Pull request merged**
